# Generated by Django 4.0.6 on 2022-12-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertifCardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('identifiant', models.TextField()),
                ('etablissement', models.CharField(max_length=120)),
                ('urlcertif', models.CharField(max_length=250)),
                ('datefield', models.DateField()),
            ],
        ),
    ]
